// =============================================================================
// auth/v1/auth.proto — домен аутентификации (v1)
// login / register / refresh / logout
//
// ТРАНСПОРТНО-НЕЙТРАЛЬНО: типы определяют ЧТО обменивается, а не КАК.
// В сообщениях нет ни HTTP-заголовков, ни REST-путей, ни status-кодов,
// ни WebTransport-потоков/датаграмм. О конкретном транспорте договор
// PROTOCOL.md; сам транспорт — сменяемый плагин (корневой AGENTS.md §7).
// =============================================================================

// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiZwoEVXNlchIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkSLgoKY3JlYXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAibwoJVG9rZW5QYWlyEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJEhkKEWFjY2Vzc19leHBpcmVzX2luGAMgASgDEhoKEnJlZnJlc2hfZXhwaXJlc19pbhgEIAEoAyJCCglBdXRoRXJyb3ISJAoEY29kZRgBIAEoDjIWLmF1dGgudjEuQXV0aEVycm9yQ29kZRIPCgdtZXNzYWdlGAIgASgJIk4KC0F1dGhTZXNzaW9uEiIKBnRva2VucxgBIAEoCzISLmF1dGgudjEuVG9rZW5QYWlyEhsKBHVzZXIYAiABKAsyDS5hdXRoLnYxLlVzZXIiLwoMTG9naW5SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJImgKDUxvZ2luUmVzcG9uc2USJwoHc2Vzc2lvbhgBIAEoCzIULmF1dGgudjEuQXV0aFNlc3Npb25IABIjCgVlcnJvchgCIAEoCzISLmF1dGgudjEuQXV0aEVycm9ySABCCQoHb3V0Y29tZSJICg9SZWdpc3RlclJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJImsKEFJlZ2lzdGVyUmVzcG9uc2USJwoHc2Vzc2lvbhgBIAEoCzIULmF1dGgudjEuQXV0aFNlc3Npb25IABIjCgVlcnJvchgCIAEoCzISLmF1dGgudjEuQXV0aEVycm9ySABCCQoHb3V0Y29tZSInCg5SZWZyZXNoUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJImcKD1JlZnJlc2hSZXNwb25zZRIkCgZ0b2tlbnMYASABKAsyEi5hdXRoLnYxLlRva2VuUGFpckgAEiMKBWVycm9yGAIgASgLMhIuYXV0aC52MS5BdXRoRXJyb3JIAEIJCgdvdXRjb21lIiYKDUxvZ291dFJlcXVlc3QSFQoNcmVmcmVzaF90b2tlbhgBIAEoCSJrCg5Mb2dvdXRSZXNwb25zZRIpCgdzdWNjZXNzGAEgASgLMhYuYXV0aC52MS5Mb2dvdXRTdWNjZXNzSAASIwoFZXJyb3IYAiABKAsyEi5hdXRoLnYxLkF1dGhFcnJvckgAQgkKB291dGNvbWUiLgoNTG9nb3V0U3VjY2VzcxIdChVyZWZyZXNoX3Rva2VuX3Jldm9rZWQYASABKAgqpQIKDUF1dGhFcnJvckNvZGUSHwobQVVUSF9FUlJPUl9DT0RFX1VOU1BFQ0lGSUVEEAASJwojQVVUSF9FUlJPUl9DT0RFX0lOVkFMSURfQ1JFREVOVElBTFMQARIfChtBVVRIX0VSUk9SX0NPREVfRU1BSUxfVEFLRU4QAhIhCh1BVVRIX0VSUk9SX0NPREVfSU5WQUxJRF9UT0tFThADEiEKHUFVVEhfRVJST1JfQ09ERV9UT0tFTl9FWFBJUkVEEAQSIAocQVVUSF9FUlJPUl9DT0RFX1JBVEVfTElNSVRFRBAFEiMKH0FVVEhfRVJST1JfQ09ERV9JTlZBTElEX1JFUVVFU1QQBhIcChhBVVRIX0VSUk9SX0NPREVfSU5URVJOQUwQB2IGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Учётная запись (минимально необходимый набор).
 *
 * @generated from message auth.v1.User
 */
export type User = Message<"auth.v1.User"> & {
  /**
   * Уникальный идентификатор пользователя.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * Момент создания учётной записи.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message auth.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * Пара токенов: короткоживущий access + долгоживущий refresh.
 *
 * @generated from message auth.v1.TokenPair
 */
export type TokenPair = Message<"auth.v1.TokenPair"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * Время жизни access-токена, сек (от момента выдачи).
   *
   * @generated from field: int64 access_expires_in = 3;
   */
  accessExpiresIn: bigint;

  /**
   * Время жизни refresh-токена, сек (от момента выдачи).
   *
   * @generated from field: int64 refresh_expires_in = 4;
   */
  refreshExpiresIn: bigint;
};

/**
 * Describes the message auth.v1.TokenPair.
 * Use `create(TokenPairSchema)` to create a new message.
 */
export const TokenPairSchema: GenMessage<TokenPair> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * Ошибка аутентификации — ТРАНСПОРТНО-НЕЙТРАЛЬНАЯ.
 * Ошибка живёт в сообщении, а не в состоянии транспорта
 * (не HTTP 4xx, не close-code потока): transport-swap не ломает семантику.
 *
 * @generated from message auth.v1.AuthError
 */
export type AuthError = Message<"auth.v1.AuthError"> & {
  /**
   * @generated from field: auth.v1.AuthErrorCode code = 1;
   */
  code: AuthErrorCode;

  /**
   * Человекочитаемое сообщение (для логов/отладки, не для UI-логиков).
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message auth.v1.AuthError.
 * Use `create(AuthErrorSchema)` to create a new message.
 */
export const AuthErrorSchema: GenMessage<AuthError> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * Успешно завершённая аутентификация: токены + пользователь.
 *
 * @generated from message auth.v1.AuthSession
 */
export type AuthSession = Message<"auth.v1.AuthSession"> & {
  /**
   * @generated from field: auth.v1.TokenPair tokens = 1;
   */
  tokens?: TokenPair | undefined;

  /**
   * @generated from field: auth.v1.User user = 2;
   */
  user?: User | undefined;
};

/**
 * Describes the message auth.v1.AuthSession.
 * Use `create(AuthSessionSchema)` to create a new message.
 */
export const AuthSessionSchema: GenMessage<AuthSession> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * @generated from message auth.v1.LoginRequest
 */
export type LoginRequest = Message<"auth.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 4);

/**
 * @generated from message auth.v1.LoginResponse
 */
export type LoginResponse = Message<"auth.v1.LoginResponse"> & {
  /**
   * @generated from oneof auth.v1.LoginResponse.outcome
   */
  outcome: {
    /**
     * @generated from field: auth.v1.AuthSession session = 1;
     */
    value: AuthSession;
    case: "session";
  } | {
    /**
     * @generated from field: auth.v1.AuthError error = 2;
     */
    value: AuthError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 5);

/**
 * @generated from message auth.v1.RegisterRequest
 */
export type RegisterRequest = Message<"auth.v1.RegisterRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * Опционально: имя для отображения.
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;
};

/**
 * Describes the message auth.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 6);

/**
 * @generated from message auth.v1.RegisterResponse
 */
export type RegisterResponse = Message<"auth.v1.RegisterResponse"> & {
  /**
   * @generated from oneof auth.v1.RegisterResponse.outcome
   */
  outcome: {
    /**
     * @generated from field: auth.v1.AuthSession session = 1;
     */
    value: AuthSession;
    case: "session";
  } | {
    /**
     * @generated from field: auth.v1.AuthError error = 2;
     */
    value: AuthError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message auth.v1.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 7);

/**
 * @generated from message auth.v1.RefreshRequest
 */
export type RefreshRequest = Message<"auth.v1.RefreshRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema: GenMessage<RefreshRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 8);

/**
 * @generated from message auth.v1.RefreshResponse
 */
export type RefreshResponse = Message<"auth.v1.RefreshResponse"> & {
  /**
   * @generated from oneof auth.v1.RefreshResponse.outcome
   */
  outcome: {
    /**
     * @generated from field: auth.v1.TokenPair tokens = 1;
     */
    value: TokenPair;
    case: "tokens";
  } | {
    /**
     * @generated from field: auth.v1.AuthError error = 2;
     */
    value: AuthError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message auth.v1.RefreshResponse.
 * Use `create(RefreshResponseSchema)` to create a new message.
 */
export const RefreshResponseSchema: GenMessage<RefreshResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 9);

/**
 * @generated from message auth.v1.LogoutRequest
 */
export type LogoutRequest = Message<"auth.v1.LogoutRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 10);

/**
 * @generated from message auth.v1.LogoutResponse
 */
export type LogoutResponse = Message<"auth.v1.LogoutResponse"> & {
  /**
   * @generated from oneof auth.v1.LogoutResponse.outcome
   */
  outcome: {
    /**
     * @generated from field: auth.v1.LogoutSuccess success = 1;
     */
    value: LogoutSuccess;
    case: "success";
  } | {
    /**
     * @generated from field: auth.v1.AuthError error = 2;
     */
    value: AuthError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message auth.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 11);

/**
 * @generated from message auth.v1.LogoutSuccess
 */
export type LogoutSuccess = Message<"auth.v1.LogoutSuccess"> & {
  /**
   * refresh-токен действительно отозван (true) либо уже был недействителен
   * (idempotency: повторный logout не ошибка).
   *
   * @generated from field: bool refresh_token_revoked = 1;
   */
  refreshTokenRevoked: boolean;
};

/**
 * Describes the message auth.v1.LogoutSuccess.
 * Use `create(LogoutSuccessSchema)` to create a new message.
 */
export const LogoutSuccessSchema: GenMessage<LogoutSuccess> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 12);

/**
 * @generated from enum auth.v1.AuthErrorCode
 */
export enum AuthErrorCode {
  /**
   * @generated from enum value: AUTH_ERROR_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * email/пароль не совпадают.
   *
   * @generated from enum value: AUTH_ERROR_CODE_INVALID_CREDENTIALS = 1;
   */
  INVALID_CREDENTIALS = 1,

  /**
   * email уже зарегистрирован.
   *
   * @generated from enum value: AUTH_ERROR_CODE_EMAIL_TAKEN = 2;
   */
  EMAIL_TAKEN = 2,

  /**
   * токен сфальсифицирован/не выдан этим сервером.
   *
   * @generated from enum value: AUTH_ERROR_CODE_INVALID_TOKEN = 3;
   */
  INVALID_TOKEN = 3,

  /**
   * токен просрочен (подходит под refresh, либо нет).
   *
   * @generated from enum value: AUTH_ERROR_CODE_TOKEN_EXPIRED = 4;
   */
  TOKEN_EXPIRED = 4,

  /**
   * превышен лимит запросов.
   *
   * @generated from enum value: AUTH_ERROR_CODE_RATE_LIMITED = 5;
   */
  RATE_LIMITED = 5,

  /**
   * невалидная структура запроса (пустое поле и т.п.).
   *
   * @generated from enum value: AUTH_ERROR_CODE_INVALID_REQUEST = 6;
   */
  INVALID_REQUEST = 6,

  /**
   * непредвиденная ошибка сервера.
   *
   * @generated from enum value: AUTH_ERROR_CODE_INTERNAL = 7;
   */
  INTERNAL = 7,
}

/**
 * Describes the enum auth.v1.AuthErrorCode.
 */
export const AuthErrorCodeSchema: GenEnum<AuthErrorCode> = /*@__PURE__*/
  enumDesc(file_auth_v1_auth, 0);

