// =============================================================================
// common/v1/envelope.proto — единственная wire-формула (v1)
//
// Envelope — единственный тип, который летает между webtransport-protobuf-angular-web/ и webtransport-protobuf-nodejs-server/.
// Внутрь — oneof payload: каждое известное сообщение (домены: auth.v1, ...).
//
// Принципы:
//  * Метаданные — ТОЛЬКО не-секретные (id, время, версия контракта).
//    Токены/пароли — исключительно в payload, никогда не в метаданные.
//  * Номера полей payload — БЛОКИ по 100 на домен (с 100):
//      домен №1 (auth.v1)  = 100–199
//      домен №2 (след.)    = 200–299
//      домен N             = 100*(N) – 100*(N)+99
//    Свободных доменов: ~194 (2047 = потолок 2-байтного тега;
//    19000–19999 зарезервировано самим protobuf — не использовать).
//    Домены не конфликтуют за номера: каждый пишет только в свой блок.
//  * 1–99 — зарезервировано (reserved 5 to 99) под будущие
//    «общие» (не-доменные) сообщения, если такие появятся.
//  * Новое сообщение = новое поле oneof СОБСТВЕННОГО БЛОКА домена
//    (аддитивно, назад-совместимо: старый приёмщик увидит payload-unset
//    и может сообщить "unknown message").
//  * Envelope — входной порт plugin-реестр-адаптера (SEAM, корневой
//    AGENTS.md §7): адаптер decode-ит ровно Envelope, смотрит
//    payload.case и диспатчит в зарегистрированный обработчик.
//
// Цена схемы (честно): поле oneof с номером 100–2047 кодируется 2-байтовым
// тегом (против 1 байта у 1–15). +1 байт на Envelope — при нашем трафике
// и размере сообщений — шум, плата за доменные блоки.
// =============================================================================

// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,import_extension=none"
// @generated from file common/v1/envelope.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { LoginRequest, LoginResponse, LogoutRequest, LogoutResponse, RefreshRequest, RefreshResponse, RegisterRequest, RegisterResponse } from "../../auth/v1/auth_pb";
import { file_auth_v1_auth } from "../../auth/v1/auth_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/envelope.proto.
 */
export const file_common_v1_envelope: GenFile = /*@__PURE__*/
  fileDesc("Chhjb21tb24vdjEvZW52ZWxvcGUucHJvdG8SCWNvbW1vbi52MSKWBAoIRW52ZWxvcGUSEgoKbWVzc2FnZV9pZBgBIAEoCRIrCgdzZW50X2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIYChBwcm90b2NvbF92ZXJzaW9uGAMgASgNEi4KDWxvZ2luX3JlcXVlc3QYZCABKAsyFS5hdXRoLnYxLkxvZ2luUmVxdWVzdEgAEjAKDmxvZ2luX3Jlc3BvbnNlGGUgASgLMhYuYXV0aC52MS5Mb2dpblJlc3BvbnNlSAASNAoQcmVnaXN0ZXJfcmVxdWVzdBhmIAEoCzIYLmF1dGgudjEuUmVnaXN0ZXJSZXF1ZXN0SAASNgoRcmVnaXN0ZXJfcmVzcG9uc2UYZyABKAsyGS5hdXRoLnYxLlJlZ2lzdGVyUmVzcG9uc2VIABIyCg9yZWZyZXNoX3JlcXVlc3QYaCABKAsyFy5hdXRoLnYxLlJlZnJlc2hSZXF1ZXN0SAASNAoQcmVmcmVzaF9yZXNwb25zZRhpIAEoCzIYLmF1dGgudjEuUmVmcmVzaFJlc3BvbnNlSAASMAoObG9nb3V0X3JlcXVlc3QYaiABKAsyFi5hdXRoLnYxLkxvZ291dFJlcXVlc3RIABIyCg9sb2dvdXRfcmVzcG9uc2UYayABKAsyFy5hdXRoLnYxLkxvZ291dFJlc3BvbnNlSABCCQoHcGF5bG9hZEoECAUQZGIGcHJvdG8z", [file_google_protobuf_timestamp, file_auth_v1_auth]);

/**
 * Единственный wire-тип обмена. См. комментарий в шапке файла.
 *
 * @generated from message common.v1.Envelope
 */
export type Envelope = Message<"common.v1.Envelope"> & {
  /**
   * UUID, сгенерированный отправителем (client id или server id).
   * Для корреляции request/response и дедупликации потерянных/повторных пакетов.
   *
   * @generated from field: string message_id = 1;
   */
  messageId: string;

  /**
   * Время отправки по часам отправителя (sender clock; не для
   * критического ordering — только для latency-замера и логов).
   *
   * @generated from field: google.protobuf.Timestamp sent_at = 2;
   */
  sentAt?: Timestamp | undefined;

  /**
   * Версия контракта, которой говорит sender (см. webtransport-protobuf-proto/PROTOCOL.md §7).
   * 1 = v1. Используется для логирования и future-совместимости;
   * не для выбора wire-формата (format задаётся самим протоколом).
   *
   * @generated from field: uint32 protocol_version = 3;
   */
  protocolVersion: number;

  /**
   * Единственный дискриминатор типа сообщения.
   * НОМЕНКЛАТУРА: домены пишут ТОЛЬКО в свой блок (auth.v1 = 100–199).
   * НОВОЕ СООБЩЕНИЕ ДОМЕНА = НОВОЕ ПОЛЕ В ЕГО БЛОКЕ.
   *
   * @generated from oneof common.v1.Envelope.payload
   */
  payload: {
    /**
     * ---- домен auth.v1: блок 100–199 (домен №1) ----
     *
     * @generated from field: auth.v1.LoginRequest login_request = 100;
     */
    value: LoginRequest;
    case: "loginRequest";
  } | {
    /**
     * @generated from field: auth.v1.LoginResponse login_response = 101;
     */
    value: LoginResponse;
    case: "loginResponse";
  } | {
    /**
     * @generated from field: auth.v1.RegisterRequest register_request = 102;
     */
    value: RegisterRequest;
    case: "registerRequest";
  } | {
    /**
     * @generated from field: auth.v1.RegisterResponse register_response = 103;
     */
    value: RegisterResponse;
    case: "registerResponse";
  } | {
    /**
     * @generated from field: auth.v1.RefreshRequest refresh_request = 104;
     */
    value: RefreshRequest;
    case: "refreshRequest";
  } | {
    /**
     * @generated from field: auth.v1.RefreshResponse refresh_response = 105;
     */
    value: RefreshResponse;
    case: "refreshResponse";
  } | {
    /**
     * @generated from field: auth.v1.LogoutRequest logout_request = 106;
     */
    value: LogoutRequest;
    case: "logoutRequest";
  } | {
    /**
     * future (в блок auth.v1): auth.v1.MeRequest / MeResponse — 108..109, ...
     * 
     * ---- домен №2 (будущий): блок 200–299 ----
     * event.v1.Heartbeat = 200; ...
     *
     * @generated from field: auth.v1.LogoutResponse logout_response = 107;
     */
    value: LogoutResponse;
    case: "logoutResponse";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message common.v1.Envelope.
 * Use `create(EnvelopeSchema)` to create a new message.
 */
export const EnvelopeSchema: GenMessage<Envelope> = /*@__PURE__*/
  messageDesc(file_common_v1_envelope, 0);

